# 動的計画法によるナップザック問題

## インストールが必要なライブラリ
Anacondaの場合は一度だけ必要となる場合がある

In [1]:
!pip install numpy

## ライブラリのインポート



In [2]:
import numpy as np

## 設定

In [3]:
w = [8,7,6,5,4,3,2,1]
v = [10,13,7,4,9,3,3,2]
N = len(w)
dp = np.zeros((N+1,10+1), dtype=int)

## 探索

In [4]:
for i in range(N):
    for j in range(10+1):
        if j >= w[i]:
            dp[i+1][j] = max(dp[i][j-w[i]]+v[i],dp[i][j])
        else:
            dp[i+1][j] = dp[i][j]
print(dp)

[[ 0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0 10 10 10]
 [ 0  0  0  0  0  0  0 13 13 13 13]
 [ 0  0  0  0  0  0  7 13 13 13 13]
 [ 0  0  0  0  0  4  7 13 13 13 13]
 [ 0  0  0  0  9  9  9 13 13 13 16]
 [ 0  0  0  3  9  9  9 13 13 13 16]
 [ 0  0  3  3  9  9 12 13 13 16 16]
 [ 0  2  3  5  9 11 12 14 15 16 18]]


## 答え

In [5]:
print(dp[N][10])

18
